In [82]:
import numpy as np # 快速操作结构数组的工具
import matplotlib.pyplot as plt  # 可视化绘制
from sklearn.linear_model import LinearRegression  # 线性回归
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, GradientBoostingRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score,roc_curve,auc
from sklearn.preprocessing import OneHotEncoder

import pandas as pd

df = pd.read_csv('./data/North/中山站/gbdt_2015_2018.csv')
# df = df[df.columns.drop(list(df.filter(regex='AVG')))]
# df = df[['PM25_NOW', 'PM2.5_AVG12', 'PM2.5_AVG6', 'DAY_OF_YEAR', 'PM2.5_AVG3', 'HOUR', 'PM2.5_DIVTSQR_T1', 'PM2.5_AVG72', 'PM2.5_T11', 'PM2.5_T1', 'MONTH', 'RH_T1', 'PM10_AVG72', 'NO2_AVG72', 'SO2_AVG72', 'PM2.5_DIVTSQR_T2', 'O3_AVG24', 'RH_T2', 'CH4_DIVTSQR_T1', 'O3_AVG72', 'CH4_AVG3', 'CH4_AVG72', 'PM10_AVG24', 'PM2.5_T12', 'CH4_T1', 'NO_AVG72', 'PM2.5_AVG24', 'CH4_T2', 'CO_AVG72', 'SO2_AVG12', 'AMB_TEMP_T2', 'NO_AVG24', 'SO2_AVG24', 'CH4_DIVTSQR_T2', 'WIND_SPEED_T1', 'NOx_AVG72', 'AMB_TEMP_T1', 'AMB_TEMP_T3', 'RH_T4', 'AMB_TEMP_T12', 'CO_AVG24', 'PM2.5_DIVTSQR_T10', 'WEEKDAY', 'THC_AVG12', 'NOx_AVG24', 'RH_T12', 'AMB_TEMP_T10', 'O3_AVG12', 'AMB_TEMP_T5', 'AMB_TEMP_T11', 'CH4_AVG6', 'PM2.5_T10', 'CH4_AVG24', 'RH_T3', 'THC_AVG72', 'NO2_AVG24', 'SO2_AVG6', 'WS_HR_T1', 'CH4_AVG12', 'PM10_AVG12', 'NO2_AVG12', 'CO_T14', 'PM10_AVG6', 'PM10_T1', 'PM10_T12', 'O3_T27', 'PM2.5_T36', 'AMB_TEMP_T4', 'RH_T11', 'NO_AVG12', 'PM10_T26', 'NMHC_AVG72', 'PM10_T27', 'O3_AVG3', 'WD_HR_T1', 'PM10_T35', 'PM2.5_T35', 'SO2_AVG3', 'THC_T1', 'RH_T10', 'RH_T9', 'WIND_SPEED_T3', 'PM10_T21', 'AMB_TEMP_T8', 'CH4_T3', 'CO_AVG12', 'PM2.5_T13', 'PM2.5_DIVTSQR_T12', 'AMB_TEMP_T9', 'PM2.5_T33', 'PM2.5_T4', 'SO2_T33', 'O3_AVG6', 'THC_AVG24', 'NO2_T34', 'NO2_T36', 'NOx_AVG12', 'PM10_T36', 'PM10_T34', 'PM10_DIVTSQR_T1', 'RH_T7', 'AMB_TEMP_T6', 'PM10_AVG3', 'O3_T13', 'SO2_T1', 'SO2_T36', 'NO2_T13', 'RH_T5', 'NO_T21', 'PM10_T31', 'NMHC_AVG24', 'O3_T28', 'O3_DIVTSQR_T1', 'AMB_TEMP_T7', 'PM10_T28', 'SO2_DIVTSQR_T1', 'SO2_T23', 'SO2_T32', 'NO2_AVG6', 'PM2.5_T32', 'PM10_DIVTSQR_T11', 'NMHC_AVG6', 'SO2_T31', 'PM2.5_DIVTSQR_T3', 'NO2_T16', 'SO2_T24', 'PM10_DIVTSQR_T5', 'SO2_T35', 'PM2.5_T30', 'SO2_DIVTSQR_T8', 'PM2.5_T28', 'SO2_T34', 'PM10_T24', 'WIND_DIREC_T2', 'PM2.5_DIVTSQR_T11', 'NO_T22', 'PM10_T14', 'O3_T1', 'CO_T20', 'PM10_T23', 'NO_T20', 'NO_T15', 'PM2.5_T2', 'THC_AVG6', 'PM10_T30', 'NO_AVG6', 'PM10_T11', 'SO2_T28', 'O3_T22', 'PM10_T32', 'WIND_SPEED_T2', 'SO2_T26', 'WD_HR_T3', 'PM10_T15', 'PM2.5_T27', 'O3_DIVTSQR_T4', 'PM10_T5', 'SO2_T22', 'NO2_T31', 'SO2_T15','WS_HR_T11', 'PM2.5_T24', 'WD_HR_T4', 'NO_AVG3', 'WIND_SPEED_T12', 'O3_DIVTSQR_T12', 'SO2_T21', 'PM10_T3', 'O3_T26', 'PM10_T8', 'SO2_T20', 'SO2_T13', 'O3_T15', 'PM10_DIVTSQR_T6', 'WS_HR_T2', 'O3_T29', 'PM10_T4', 'NO_T19', 'NO_T13', 'WD_HR_T12', 'NO_T24', 'SO2_DIVTSQR_T7', 'WS_HR_T8', 'O3_T25', 'CO_T13', 'SO2_T10', 'CO_T28', 'O3_T19', 'CO_T36', 'WD_HR_T7', 'PM10_T13', 'NO_T14', 'WD_HR_T11', 'SO2_T17', 'RH_T6', 'NO_T10', 'PM2.5_T15', 'PM2.5_T31', 'RH_T8', 'PM2.5_DIVTSQR_T5', 'NOx_T36']]

X_train, y_train = df.drop(['PM25_NOW'], axis=1), df['PM25_NOW']

df_test = pd.read_csv('./data/North/中山站/gbdt_2019.csv')
# df_test = df_test[df_test.columns.drop(list(df_test.filter(regex='AVG')))]
# df_test = df_test[['PM25_NOW', 'PM2.5_AVG12', 'PM2.5_AVG6', 'DAY_OF_YEAR', 'PM2.5_AVG3', 'HOUR', 'PM2.5_DIVTSQR_T1', 'PM2.5_AVG72', 'PM2.5_T11', 'PM2.5_T1', 'MONTH', 'RH_T1', 'PM10_AVG72', 'NO2_AVG72', 'SO2_AVG72', 'PM2.5_DIVTSQR_T2', 'O3_AVG24', 'RH_T2', 'CH4_DIVTSQR_T1', 'O3_AVG72', 'CH4_AVG3', 'CH4_AVG72', 'PM10_AVG24', 'PM2.5_T12', 'CH4_T1', 'NO_AVG72', 'PM2.5_AVG24', 'CH4_T2', 'CO_AVG72', 'SO2_AVG12', 'AMB_TEMP_T2', 'NO_AVG24', 'SO2_AVG24', 'CH4_DIVTSQR_T2', 'WIND_SPEED_T1', 'NOx_AVG72', 'AMB_TEMP_T1', 'AMB_TEMP_T3', 'RH_T4', 'AMB_TEMP_T12', 'CO_AVG24', 'PM2.5_DIVTSQR_T10', 'WEEKDAY', 'THC_AVG12', 'NOx_AVG24', 'RH_T12', 'AMB_TEMP_T10', 'O3_AVG12', 'AMB_TEMP_T5', 'AMB_TEMP_T11', 'CH4_AVG6', 'PM2.5_T10', 'CH4_AVG24', 'RH_T3', 'THC_AVG72', 'NO2_AVG24', 'SO2_AVG6', 'WS_HR_T1', 'CH4_AVG12', 'PM10_AVG12', 'NO2_AVG12', 'CO_T14', 'PM10_AVG6', 'PM10_T1', 'PM10_T12', 'O3_T27', 'PM2.5_T36', 'AMB_TEMP_T4', 'RH_T11', 'NO_AVG12', 'PM10_T26', 'NMHC_AVG72', 'PM10_T27', 'O3_AVG3', 'WD_HR_T1', 'PM10_T35', 'PM2.5_T35', 'SO2_AVG3', 'THC_T1', 'RH_T10', 'RH_T9', 'WIND_SPEED_T3', 'PM10_T21', 'AMB_TEMP_T8', 'CH4_T3', 'CO_AVG12', 'PM2.5_T13', 'PM2.5_DIVTSQR_T12', 'AMB_TEMP_T9', 'PM2.5_T33', 'PM2.5_T4', 'SO2_T33', 'O3_AVG6', 'THC_AVG24', 'NO2_T34', 'NO2_T36', 'NOx_AVG12', 'PM10_T36', 'PM10_T34', 'PM10_DIVTSQR_T1', 'RH_T7', 'AMB_TEMP_T6', 'PM10_AVG3', 'O3_T13', 'SO2_T1', 'SO2_T36', 'NO2_T13', 'RH_T5', 'NO_T21', 'PM10_T31', 'NMHC_AVG24', 'O3_T28', 'O3_DIVTSQR_T1', 'AMB_TEMP_T7', 'PM10_T28', 'SO2_DIVTSQR_T1', 'SO2_T23', 'SO2_T32', 'NO2_AVG6', 'PM2.5_T32', 'PM10_DIVTSQR_T11', 'NMHC_AVG6', 'SO2_T31', 'PM2.5_DIVTSQR_T3', 'NO2_T16', 'SO2_T24', 'PM10_DIVTSQR_T5', 'SO2_T35', 'PM2.5_T30', 'SO2_DIVTSQR_T8', 'PM2.5_T28', 'SO2_T34', 'PM10_T24', 'WIND_DIREC_T2', 'PM2.5_DIVTSQR_T11', 'NO_T22', 'PM10_T14', 'O3_T1', 'CO_T20', 'PM10_T23', 'NO_T20', 'NO_T15', 'PM2.5_T2', 'THC_AVG6', 'PM10_T30', 'NO_AVG6', 'PM10_T11', 'SO2_T28', 'O3_T22', 'PM10_T32', 'WIND_SPEED_T2', 'SO2_T26', 'WD_HR_T3', 'PM10_T15', 'PM2.5_T27', 'O3_DIVTSQR_T4', 'PM10_T5', 'SO2_T22', 'NO2_T31', 'SO2_T15','WS_HR_T11', 'PM2.5_T24', 'WD_HR_T4', 'NO_AVG3', 'WIND_SPEED_T12', 'O3_DIVTSQR_T12', 'SO2_T21', 'PM10_T3', 'O3_T26', 'PM10_T8', 'SO2_T20', 'SO2_T13', 'O3_T15', 'PM10_DIVTSQR_T6', 'WS_HR_T2', 'O3_T29', 'PM10_T4', 'NO_T19', 'NO_T13', 'WD_HR_T12', 'NO_T24', 'SO2_DIVTSQR_T7', 'WS_HR_T8', 'O3_T25', 'CO_T13', 'SO2_T10', 'CO_T28', 'O3_T19', 'CO_T36', 'WD_HR_T7', 'PM10_T13', 'NO_T14', 'WD_HR_T11', 'SO2_T17', 'RH_T6', 'NO_T10', 'PM2.5_T15', 'PM2.5_T31', 'RH_T8', 'PM2.5_DIVTSQR_T5', 'NOx_T36']]
X_test, y_test = df_test.drop(['PM25_NOW'], axis=1), df_test['PM25_NOW']

In [83]:
X_test.describe()

PM2.5_T1     PM2.5_T2     PM2.5_T3     PM2.5_T4     PM2.5_T5  \
count  8676.000000  8676.000000  8676.000000  8676.000000  8676.000000   
mean     14.463392    14.463239    14.462547    14.461971    14.461279   
std       9.137906     9.138020     9.138585     9.139277     9.140068   
min       1.000000     1.000000     1.000000     1.000000     1.000000   
25%       8.000000     8.000000     8.000000     8.000000     8.000000   
50%      13.000000    13.000000    13.000000    13.000000    13.000000   
75%      19.000000    19.000000    19.000000    19.000000    19.000000   
max      83.000000    83.000000    83.000000    83.000000    83.000000   

          PM2.5_T6     PM2.5_T7     PM2.5_T8     PM2.5_T9    PM2.5_T10  ...  \
count  8676.000000  8676.000000  8676.000000  8676.000000  8676.000000  ...   
mean     14.461049    14.461971    14.462662    14.463700    14.464276  ...   
std       9.140307     9.139756     9.139267     9.138249     9.137621  ...   
min       1.000000     1.000000     1.000000     1.000000     1.000000  ...   
25%       8.000000     8.000000     8.000000     8.000000     8.000000  ...   
50%      13.000000    13.000000    13.000000    13.000000    13.000000  ...   
75%      19.000000    19.000000    19.000000    19.000000    19.000000  ...   
max      83.000000    83.000000    83.000000    83.000000    83.000000  ...   

       THC_DIVTSQR_T7  THC_DIVTSQR_T8  THC_DIVTSQR_T9  THC_DIVTSQR_T10  \
count     8676.000000     8676.000000     8676.000000      8676.000000   
mean         0.040415        0.030943        0.024449         0.019804   
std          0.004277        0.003275        0.002587         0.002096   
min          0.029469        0.022562        0.017827         0.014440   
25%          0.038776        0.029687        0.023457         0.019000   
50%          0.038776        0.029687        0.023457         0.019000   
75%          0.040837        0.031266        0.024704         0.020010   
max          0.081633        0.062500        0.049383         0.040000   

       THC_DIVTSQR_T11  THC_DIVTSQR_T12  DAY_OF_YEAR         HOUR  \
count      8676.000000      8676.000000  8676.000000  8676.000000   
mean          0.016367         0.013753   183.749654    12.508299   
std           0.001732         0.001455   104.362275     6.922581   
min           0.011934         0.010028     3.000000     1.000000   
25%           0.015702         0.013194    93.000000     7.000000   
50%           0.015702         0.013194   184.000000    13.000000   
75%           0.016537         0.013896   274.000000    19.000000   
max           0.033058         0.027778   364.000000    24.000000   

           WEEKDAY        MONTH  
count  8676.000000  8676.000000  
mean      3.001383     6.579530  
std       2.005985     3.421346  
min       0.000000     1.000000  
25%       1.000000     4.000000  
50%       3.000000     7.000000  
75%       5.000000    10.000000  
max       6.000000    12.000000  

[8 rows x 660 columns]

In [84]:
# 弱分类器的数目
n_estimator = 80
# 随机生成分类数据。
# X, y = make_classification(n_samples=80000,n_features=20,n_classes=2)

# 切分为测试集和训练集，比例0.5
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)
# 将训练集切分为两部分，一部分用于训练GBDT模型，另一部分输入到训练好的GBDT模型生成GBDT特征，然后作为LR的特征。这样分成两部分是为了防止过拟合。
X_train_gbdt, X_train_lr, y_train_gbdt, y_train_lr = train_test_split(X_train, y_train, test_size=0.5, random_state=42)
# 调用GBDT分类模型。
gbdt = GradientBoostingRegressor(n_estimators=n_estimator, verbose=1)
# gbdt = GradientBoostingRegressor(verbose=1)
# 调用one-hot编码。
one_hot = OneHotEncoder()
# 调用LR分类模型。
# lr = LogisticRegression()
lr = LinearRegression()


'''使用X_train训练GBDT模型，后面用此模型构造特征'''
gbdt.fit(X_train_gbdt, y_train_gbdt)
# gbdt.fit(X_train, y_train)


      Iter       Train Loss   Remaining Time 
         1         136.7023           40.76s
         2         131.6135           39.57s
         3         127.2802           39.09s
         4         123.5363           38.64s
         5         120.5134           37.91s
         6         117.6293           37.20s
         7         115.3133           36.75s
         8         113.1807           36.15s
         9         111.1545           35.78s
        10         109.2369           35.35s
        20          98.1625           30.53s
        30          93.1718           25.15s
        40          90.0569           19.66s
        50          87.6770           14.32s
        60          85.6027            9.34s
        70          83.8923            4.60s
        80          82.4836            0.00s


GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=80,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=1, warm_start=False)

In [85]:
X_leaf_index = gbdt.apply(X_train_gbdt)
# X_leaf_index = gbdt.apply(X_train)

In [86]:
np.shape(X_leaf_index)

(17466, 80)

In [87]:
# X_leaf_index = gbdt.apply(X_train_gbdt)[:, :, 0]
X_leaf_index = gbdt.apply(X_train_gbdt)[:, :]
# X_leaf_index = gbdt.apply(X_train)[:, :]

In [88]:
np.shape(X_leaf_index)

(17466, 80)

In [89]:
X_lr_leaf_index = gbdt.apply(X_train_lr)[:, :] # apply返回每个样本在每科树中所属的叶子节点索引。行数为样本数，列数为树数目。值为在每个数的叶子索引
# X_lr_leaf_index = gbdt.apply(X_train)[:, :] # apply返回每个样本在每科树中所属的叶子节点索引。行数为样本数，列数为树数目。值为在每个数的叶子索引
print('每个样本在每个树中所属的叶子索引\n',X_leaf_index)


每个样本在每个树中所属的叶子索引
 [[ 6.  7. 10. ...  4. 12.  3.]
 [ 3.  6.  4. ...  3. 12.  3.]
 [ 3.  6.  4. ...  3. 12.  3.]
 ...
 [ 4.  4.  6. ...  3. 11.  3.]
 [13. 10. 13. ...  3. 12. 11.]
 [ 3.  4.  4. ...  3. 11.  3.]]


In [90]:
X_leaf_index

array([[ 6.,  7., 10., ...,  4., 12.,  3.],
       [ 3.,  6.,  4., ...,  3., 12.,  3.],
       [ 3.,  6.,  4., ...,  3., 12.,  3.],
       ...,
       [ 4.,  4.,  6., ...,  3., 11.,  3.],
       [13., 10., 13., ...,  3., 12., 11.],
       [ 3.,  4.,  4., ...,  3., 11.,  3.]])

In [91]:
len(X_leaf_index[0])

80

In [92]:
# fit one-hot编码器
one_hot.fit(X_leaf_index)  # 训练one-hot编码，就是识别每列有多少可取值
X_lr_one_hot = one_hot.transform(X_lr_leaf_index)  # 将训练数据，通过gbdt树，形成的叶子节点（每个叶子代表了原始特征的一种组合）索引，编码成one0-hot特征。
# 编码后的每个特征代表原来的一批特征的组合。


/Users/yoeugene/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [93]:
# print(X_lr_one_hot)

In [94]:
y_train_lr
# y_train

3248     27.0
29928    24.0
23101     9.0
12536    11.0
3219     26.0
         ... 
29653    35.0
28574    14.0
28951    14.0
1983      8.0
26921    12.0
Name: PM25_NOW, Length: 17466, dtype: float64

In [95]:
''' 
使用训练好的GBDT模型构建特征，然后将特征经过one-hot编码作为新的特征输入到LR模型训练。
'''

# 使用lr训练gbdt的特征组合
print('使用逻辑回归训练GBDT组合特征的结果')
lr.fit(X_lr_one_hot, y_train_lr)
# lr.fit(X_lr_one_hot, y_train)

使用逻辑回归训练GBDT组合特征的结果


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [96]:
# 用训练好的LR模型多X_test做预测
# y_pred_grd_lm = lr.predict_proba(one_hot.transform(gbdt.apply(X_test)[:, :, 0]))[:, 1]  # 获取测试集正样本的概率
y_pred_grd_lm = lr.predict(one_hot.transform(gbdt.apply(X_test)[:, :]))[:]  # 获取测试集正样本的概率

sum_of_absolute_err = sum(abs(y_pred_grd_lm - y_test))
num_of_test_case = len(y_test)

print('Average MAE = ' + str(sum_of_absolute_err / num_of_test_case))

Average MAE = 6.164671750208347


In [81]:

# y_pre= lr.predict(one_hot.transform(gbdt.apply(X_test)[:, :, 0]))  # 获取测试集正样本的概率
 
# y_pro= lr.predict_proba(one_hot.transform(gbdt.apply(X_test)[:, :, 0]))[:, 1]  # 获取测试集正样本的概率



In [32]:
# from sklearn import metrics


# print("AUC Score :",(metrics.roc_auc_score(y_test, y_pro)))   
# print("Accuracy :",(metrics.accuracy_score(y_test, y_pre)))  